# 基本はgithub.comのリポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = "sheerun/vim-polyglot"

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "Shougo/neocomplete.vim"

[[plugins]]
repo = "suan/vim-instant-markdown"

[[plugins]]
repo = "godlygeek/tabular"

[[plugins]]
repo = "plasticboy/vim-markdown"
